#!/usr/bin/env python3
"""Generate the C header and the Python module from the field specification.

    python python/tools/gen_codec.py projects/P09-payload-codec/fields.py --out-c c/payload --out-py python/firmkit --out-rs projects/P09-payload-codec/rust/src
    python python/tools/gen_codec.py projects/P09-payload-codec/fields.py --out-c c/payload --out-py python/firmkit --out-rs projects/P09-payload-codec/rust/src --check

The generator earns its place by removing a class of defect rather than by
saving typing: a bit layout written out twice will diverge, and it will diverge
silently, because both sides will still produce five bytes.

What it cannot do is check that the layout is the one the specification
intended. That is what test/vectors.json is for, and no generator has ever
touched that file.

--check regenerates into memory and compares against what is committed, exiting
non-zero on a difference. That is the continuous integration gate: a
specification change cannot be merged without the regeneration.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

BANNER = "Generated by tools/gen_codec.py from {spec}. Do not edit."


def load_spec(path: Path):
    """Read the specification as source text and execute it.

    Deliberately not importlib.util.spec_from_file_location plus exec_module,
    which is the obvious way to do this and bit me on Thursday 1 October 2026.
    That path goes through the bytecode cache, and the cache is keyed on the
    source file's size and modification time. An edit that changes a width from
    18 to 17 leaves the size identical, so a stale __pycache__ entry can shadow
    the real file and the generator silently emits headers for a layout nobody
    wrote. It took a contradiction between grep and the generator to notice.

    Compiling the text that is actually on disk removes the whole class of
    problem. For a file that is the specification, being deterministic matters
    more than being idiomatic.
    """
    source = path.read_text(encoding="utf-8")
    namespace: dict = {"__file__": str(path), "__name__": "_fields_spec"}
    exec(compile(source, str(path), "exec"), namespace)  # noqa: S102
    try:
        return namespace["FIELDS"], namespace["TOTAL_BITS"]
    except KeyError as exc:
        raise SystemExit(
            "{} does not define {}".format(path, exc.args[0])
        ) from exc


def offsets(fields):
    """Bit offset of each field from the first bit on the wire."""
    pos, out = 0, []
    for name, width, signed, note in fields:
        out.append((name, width, signed, note, pos))
        pos += width
    return out


def emit_c(fields, total_bits, spec_name: str) -> str:
    lines = [
        "/* " + BANNER.format(spec=spec_name),
        " *",
        " * Most significant bit first. Bit {} is the first bit on the wire.".format(
            total_bits - 1
        ),
        " * Every PAYLOAD_O_ value is an offset in bits from the first bit on",
        " * the wire, counting up, so version is at offset 0. That is not the",
        " * same numbering as the bit-position column in docs/bitorder.md,",
        " * which counts down from {} the way a reference manual numbers a".format(
            total_bits - 1
        ),
        " * register. Both describe the same layout.",
        " *",
        " * docs/bitorder.md is normative; this file is derived from it.",
        " */",
        "#ifndef PAYLOAD_FIELDS_H",
        "#define PAYLOAD_FIELDS_H",
        "",
        "#define PAYLOAD_BITS  {}u".format(total_bits),
        "#define PAYLOAD_BYTES {}u".format(total_bits // 8),
        "",
    ]
    for name, width, signed, note, pos in offsets(fields):
        upper = name.upper()
        mask = (1 << width) - 1
        lines.append("/* {}: {} */".format(name, note))
        lines.append("#define PAYLOAD_W_{:<9} {}u".format(upper, width))
        lines.append("#define PAYLOAD_O_{:<9} {}u".format(upper, pos))
        lines.append("#define PAYLOAD_M_{:<9} 0x{:X}u".format(upper, mask))
        if signed:
            lines.append(
                "#define PAYLOAD_SIGNED_{:<4} 1".format(upper)
            )
        lines.append("")
    lines.append("#endif /* PAYLOAD_FIELDS_H */")
    return "\n".join(lines) + "\n"


def emit_py(fields, total_bits, spec_name: str) -> str:
    lines = [
        "# " + BANNER.format(spec=spec_name),
        "#",
        "# Most significant bit first. Bit {} is the first bit on the wire.".format(
            total_bits - 1
        ),
        "# Fields are listed in wire order. A reader walks them in this order",
        "# from the first bit on the wire, with no padding between them.",
        "#",
        "# docs/bitorder.md is normative; this file is derived from it.",
        "",
        "FIELDS = [",
    ]
    for name, width, signed, note in fields:
        lines.append(
            "    ({!r}, {}, {}, {!r}),".format(name, width, signed, note)
        )
    lines += [
        "]",
        "",
        "TOTAL_BITS = {}".format(total_bits),
        "TOTAL_BYTES = {}".format(total_bits // 8),
        "",
    ]
    return "\n".join(lines)


def emit_rs(fields, total_bits, spec_name: str) -> str:
    """The same table again in Rust, for the same reason the C header is
    generated: a bit layout written out twice diverges silently, because both
    sides still produce five bytes. Four languages make that four times over."""
    lines = [
        "// " + BANNER.format(spec=spec_name),
        "//",
        "// Most significant bit first. Bit {} is the first bit on the wire.".format(
            total_bits - 1
        ),
        "// Every O_ value is an offset in bits from the first bit on the wire,",
        "// counting up, so version is at offset 0. That is not the same",
        "// numbering as the bit-position column in docs/bitorder.md, which",
        "// counts down from {} the way a reference manual numbers a register.".format(
            total_bits - 1
        ),
        "// Both describe the same layout.",
        "//",
        "// docs/bitorder.md is normative; this file is derived from it.",
        "",
        "pub const PAYLOAD_BITS: usize = {};".format(total_bits),
        "pub const PAYLOAD_BYTES: usize = {};".format(total_bits // 8),
        "",
    ]
    for name, width, signed, note, pos in offsets(fields):
        upper = name.upper()
        mask = (1 << width) - 1
        lines.append("/// {}: {}".format(name, note))
        lines.append("pub const W_{}: u32 = {};".format(upper, width))
        lines.append("pub const O_{}: usize = {};".format(upper, pos))
        lines.append("pub const M_{}: u32 = 0x{:X};".format(upper, mask))
        if signed:
            lines.append("pub const SIGNED_{}: bool = true;".format(upper))
        lines.append("")
    return "\n".join(lines)


def write_or_check(path: Path, text: str, check: bool) -> bool:
    """Return True when the file on disk already matches."""
    if check:
        if not path.exists():
            print("MISSING  {}".format(path))
            return False
        current = path.read_text(encoding="utf-8")
        if current != text:
            print("STALE    {}".format(path))
            return False
        print("current  {}".format(path))
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print("wrote    {}".format(path))
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("spec", type=Path, help="the field specification, projects/P09-payload-codec/fields.py")
    ap.add_argument("--out-c", type=Path, required=True, help="directory for payload_fields.h")
    ap.add_argument("--out-py", type=Path, required=True, help="directory for payload_fields.py")
    ap.add_argument("--out-rs", type=Path, required=True, help="directory for fields.rs")
    ap.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed files instead of writing, and fail on a difference",
    )
    args = ap.parse_args(argv)

    fields, total_bits = load_spec(args.spec)
    spec_name = args.spec.as_posix()

    ok = write_or_check(
        args.out_c / "payload_fields.h", emit_c(fields, total_bits, spec_name), args.check
    )
    ok = write_or_check(
        args.out_py / "payload_fields.py", emit_py(fields, total_bits, spec_name), args.check
    ) and ok
    ok = write_or_check(
        args.out_rs / "fields.rs", emit_rs(fields, total_bits, spec_name), args.check
    ) and ok

    if args.check and not ok:
        print(
            "\nthe generated files do not match the specification.\n"
            "run: python python/tools/gen_codec.py projects/P09-payload-codec/fields.py --out-c c/payload --out-py python/firmkit --out-rs projects/P09-payload-codec/rust/src"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
