# Generated by tools/gen_codec.py from projects/P09-payload-codec/fields.py. Do not edit.
#
# Most significant bit first. Bit 39 is the first bit on the wire.
# Fields are listed in wire order. A reader walks them in this order
# from the first bit on the wire, with no padding between them.
#
# docs/bitorder.md is normative; this file is derived from it.

FIELDS = [
    ('version', 3, False, 'format version, 0 to 7'),
    ('flags', 4, False, 'bit 0 retry, bit 1 forced, bits 2 and 3 spare'),
    ('sequence', 9, False, 'wraps at 512'),
    ('feature', 18, True, "two's complement, scaled by 1/16"),
    ('battery', 6, False, 'units of 50 mV above 2.00 V'),
]

TOTAL_BITS = 40
TOTAL_BYTES = 5
