/* Generated by tools/gen_codec.py from projects/P09-payload-codec/fields.py. Do not edit.
 *
 * Most significant bit first. Bit 39 is the first bit on the wire.
 * Every PAYLOAD_O_ value is an offset in bits from the first bit on
 * the wire, counting up, so version is at offset 0. That is not the
 * same numbering as the bit-position column in docs/bitorder.md,
 * which counts down from 39 the way a reference manual numbers a
 * register. Both describe the same layout.
 *
 * docs/bitorder.md is normative; this file is derived from it.
 */
#ifndef PAYLOAD_FIELDS_H
#define PAYLOAD_FIELDS_H

#define PAYLOAD_BITS  40u
#define PAYLOAD_BYTES 5u

/* version: format version, 0 to 7 */
#define PAYLOAD_W_VERSION   3u
#define PAYLOAD_O_VERSION   0u
#define PAYLOAD_M_VERSION   0x7u

/* flags: bit 0 retry, bit 1 forced, bits 2 and 3 spare */
#define PAYLOAD_W_FLAGS     4u
#define PAYLOAD_O_FLAGS     3u
#define PAYLOAD_M_FLAGS     0xFu

/* sequence: wraps at 512 */
#define PAYLOAD_W_SEQUENCE  9u
#define PAYLOAD_O_SEQUENCE  7u
#define PAYLOAD_M_SEQUENCE  0x1FFu

/* feature: two's complement, scaled by 1/16 */
#define PAYLOAD_W_FEATURE   18u
#define PAYLOAD_O_FEATURE   16u
#define PAYLOAD_M_FEATURE   0x3FFFFu
#define PAYLOAD_SIGNED_FEATURE 1

/* battery: units of 50 mV above 2.00 V */
#define PAYLOAD_W_BATTERY   6u
#define PAYLOAD_O_BATTERY   34u
#define PAYLOAD_M_BATTERY   0x3Fu

#endif /* PAYLOAD_FIELDS_H */
