// Generated by tools/gen_codec.py from projects/P09-payload-codec/fields.py. Do not edit.
//
// Most significant bit first. Bit 39 is the first bit on the wire.
// Every O_ value is an offset in bits from the first bit on the wire,
// counting up, so version is at offset 0. That is not the same
// numbering as the bit-position column in docs/bitorder.md, which
// counts down from 39 the way a reference manual numbers a register.
// Both describe the same layout.
//
// docs/bitorder.md is normative; this file is derived from it.

pub const PAYLOAD_BITS: usize = 40;
pub const PAYLOAD_BYTES: usize = 5;

/// version: format version, 0 to 7
pub const W_VERSION: u32 = 3;
pub const O_VERSION: usize = 0;
pub const M_VERSION: u32 = 0x7;

/// flags: bit 0 retry, bit 1 forced, bits 2 and 3 spare
pub const W_FLAGS: u32 = 4;
pub const O_FLAGS: usize = 3;
pub const M_FLAGS: u32 = 0xF;

/// sequence: wraps at 512
pub const W_SEQUENCE: u32 = 9;
pub const O_SEQUENCE: usize = 7;
pub const M_SEQUENCE: u32 = 0x1FF;

/// feature: two's complement, scaled by 1/16
pub const W_FEATURE: u32 = 18;
pub const O_FEATURE: usize = 16;
pub const M_FEATURE: u32 = 0x3FFFF;
pub const SIGNED_FEATURE: bool = true;

/// battery: units of 50 mV above 2.00 V
pub const W_BATTERY: u32 = 6;
pub const O_BATTERY: usize = 34;
pub const M_BATTERY: u32 = 0x3F;
