"""Every firmware target the build defines has to appear in docs/building.md.

WHY THIS EXISTS. docs/building.md has a section called "The real target names"
which opens with "Only targets that exist can be built" and is meant to be the
list a reader trusts instead of the chapters, whose artefact names are older
than the build and several of which name nothing.

On Tuesday 6 October 2026 that table was missing `p01-pll280`, which had existed
since Sunday 4 October 2026, runs on the board, and is the image that produced
every clock measurement in this volume. Four target families were listed and
five exist.

THAT IS THE SECOND TABLE MAINTAINED BY HAND TO DRIFT ON THE SAME DAY. The first
was the test list in .github/workflows/code.yml, which had never run four test
files; 4055069 fixed the cause by running the whole directory, and
python/tests/test_ci_runs_every_test.py guards that. This is the same shape:
a list of things, written out by a person, that nothing compares against
reality.

HOW IT MATCHES, and the rule is deliberately loose. CMake generates several
target names from loops, so `p02-ring-${P02_NAME}` becomes four real targets and
the table quite reasonably writes them as `p02-ring-<mode>, four of them`.
Requiring exact names would force the table to list sixteen rows and would make
it worse to read. So what is required is that the LITERAL PREFIX of every
add_firmware name appears somewhere in the table: `p02-ring-` for that family,
`p01-pll280` in full for a target with no variable in it.

A name that is nothing but a variable, `${P09_TARGET}`, has no literal prefix.
Those are resolved from the `set()` lines that assign them, and if one cannot be
resolved this test FAILS rather than skipping it, because a target nobody can
name is exactly the one that goes missing.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent.parent
CMAKE = ROOT / "CMakeLists.txt"
DOC = ROOT / "docs" / "building.md"

ADD_FIRMWARE = re.compile(r"add_firmware\(\s*([^\s)]+)")
SET_SIMPLE = re.compile(r"^\s*set\(\s*([A-Za-z0-9_]+)\s+([^\s)]+)", re.MULTILINE)


def literal_prefix(name: str) -> str:
    """The part of a CMake target name before any variable reference."""
    cut = name.find("${")
    return name if cut < 0 else name[:cut]


def target_names() -> list[str]:
    text = CMAKE.read_text(encoding="utf-8")
    found = ADD_FIRMWARE.findall(text)
    assert found, "no add_firmware calls in {}, so this guard would pass over an " \
                  "empty list".format(CMAKE)

    assigns = {}
    for var, value in SET_SIMPLE.findall(text):
        assigns.setdefault(var, []).append(value)

    out = []
    for name in found:
        prefix = literal_prefix(name)
        if prefix:
            out.append(prefix)
            continue
        var = re.fullmatch(r"\$\{([A-Za-z0-9_]+)\}", name)
        if var is None or var.group(1) not in assigns:
            pytest.fail(
                "add_firmware({}) has no literal prefix and no set() line this "
                "test can resolve, so the target cannot be named and cannot be "
                "checked against the table. Either give it a literal prefix or "
                "teach this test how it is assigned.".format(name))
        for value in assigns[var.group(1)]:
            out.append(literal_prefix(value) or value)
    return sorted(set(out))


def table_text() -> str:
    text = DOC.read_text(encoding="utf-8")
    start = text.find("## The real target names")
    assert start >= 0, "docs/building.md has no 'The real target names' section"
    end = text.find("\n## ", start + 1)
    return text[start:] if end < 0 else text[start:end]


def test_the_table_exists_and_is_not_empty():
    table = table_text()
    rows = [line for line in table.split("\n") if line.strip().startswith("|")]
    assert len(rows) >= 4, (
        "the target table has {} table lines, too few for this guard to mean "
        "anything".format(len(rows)))


def test_every_firmware_target_is_in_the_table():
    table = table_text()
    names = target_names()
    missing = [n for n in names if n not in table]
    assert not missing, (
        "{} of {} firmware target name(s) do not appear in docs/building.md's "
        "'The real target names' section: {}.\n"
        "That section is the list a reader is told to trust instead of the "
        "chapters, so a target missing from it is a target nobody knows they "
        "can build. Add a row, or if the name is generated by a loop, make sure "
        "its literal prefix appears.".format(len(missing), len(names), missing))


def test_the_table_names_no_target_that_does_not_exist():
    """The other direction, which is the worse failure of the two.

    A missing row hides a target that works. A row for a target that does not
    exist sends a reader to a build that fails, and the section's own first
    sentence promises it will not: "Only targets that exist can be built."

    Matched on the backtick-quoted names in the table, which is how every row
    writes them, and loop families are recognised by their literal prefix the
    same way the forward check does it.
    """
    table = table_text()
    names = target_names()
    quoted = re.findall(r"`([a-z0-9][a-z0-9-]*(?:<[a-z]+>)?[a-z0-9-]*)`", table)
    unknown = []
    for q in quoted:
        stem = q.split("<")[0]
        if not any(stem.startswith(n) or n.startswith(stem) for n in names):
            unknown.append(q)
    assert not unknown, (
        "docs/building.md names target(s) the build does not define: {}.\n"
        "Known target names or prefixes: {}".format(unknown, names))
